language: python
env:
  - TOX_ENV=py27
  - TOX_ENV=py26
  - TOX_ENV=py34
  - TOX_ENV=py33
  - TOX_ENV=py32
  - TOX_ENV=pypy
  - TOX_ENV=flakes
install:
  - pip install tox
script:
  tox -e $TOX_ENV
matrix:
  fast_finish: true
